name: Feature Update
description: Request to update to a newer version of the framework(s) or other such technologies
assignees: ["kirby-b"]
labels: ["feature_update"]
title: "[FEAT_UPD]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this change hasn't been already submitted by someone by looking through other open/closed issues. If you have questions about what technologies/frameworks are used, submit a question instead.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What changes would you like to propose
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the question like links, screeenshots, etc.
