name: Feature Fix
description: Request to fix a game feature
assignees: ["kirby-b"]
labels: ["enhancement", "bug"]
title: "[FIX]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature fix hasn't been already submitted by someone by looking through other open/closed issues
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of what the problem is
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, etc.
