name: Question
description: Ask a question regarding the software
assignees: ["kirby-b"]
labels: ["question"]
title: "[Q]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this question hasn't been already submitted by someone by looking through other open/closed issues
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: State your question and what software it is regarding
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the question like links, screeenshots, etc.
